# Generated by Django 3.0.5 on 2020-05-21 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('phone', models.IntegerField(unique=True)),
                ('total_due', models.FloatField(default=0)),
                ('reference', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'cutomer',
            },
        ),
        migrations.CreateModel(
            name='FixedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('time', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'fixedproduct',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(default=datetime.date.today)),
                ('pay', models.IntegerField()),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='YardProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=50)),
                ('yard', models.IntegerField()),
                ('gira', models.IntegerField()),
                ('per_yard_price', models.IntegerField()),
                ('total_price', models.FloatField(default=0)),
                ('time', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'yardproduct',
            },
        ),
    ]
