# Generated by Django 3.0.5 on 2020-05-22 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='customer',
            order_with_respect_to='name',
        ),
    ]
