# Generated by Django 3.0.5 on 2020-05-22 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200522_0547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='customer',
            order_with_respect_to=None,
        ),
    ]
