# Generated by Django 3.0.5 on 2020-05-22 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer_fixedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='yardproduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.YardProduct'),
        ),
    ]
