# Generated by Django 3.0.5 on 2020-05-22 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customer_yardproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='fixedproduct',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='yardproduct',
        ),
        migrations.AddField(
            model_name='fixedproduct',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='yardproduct',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
    ]
