# Generated by Django 3.0.5 on 2020-05-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20200522_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='total_due',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
