# Generated by Django 3.0.5 on 2020-05-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20200522_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yardproduct',
            name='total_price',
            field=models.FloatField(null=True),
        ),
    ]
