# Generated by Django 3.0.5 on 2020-05-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20200522_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yardproduct',
            name='total_price',
            field=models.FloatField(default=5.0),
        ),
    ]
